---
# defaults/main.yml (clickhouse)
# Prefix : clickhouse

- name: Pre-check variables
  import_tasks: pre_check.yml
  tags: ["pre_check"]

- name: Install tasks
  import_tasks: install.yml
  when:
    - clickhouse_install_flag | bool
  tags: ["install"]

- name: Configure tasks
  import_tasks: configure.yml
  tags: ["configure"]
