---
# handlers/main.yml (clickhouse)
# Prefix : clickhouse

- name: Restart clickhouse-server
  systemd:
    name: clickhouse-server.service
    state: restarted

- name: "Print warning for clickhouse (Check for deleted variables)"
  debug:
    msg: "{{ __clickhouse_check_deleted_vars.stdout_lines }}"
  failed_when: yes
  ignore_errors: yes
